# Generated by Django 2.2 on 2020-10-15 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='etiqueta',
            field=models.SlugField(null=True, verbose_name='Etiqueta'),
        ),
    ]
